services:
  crw-local:
    build: .
    volumes:
      - ./data/images:/var/www/html/images
      # Extensions with customizations, others are copied on image build
      # Settings
      - ./conf/LocalSettings.php:/var/www/html/LocalSettings.php
      - ./conf/LocalSettings:/var/www/html/LocalSettings
      # Semantics Configuration
      - ./data/semantics:/var/www/html/semantics_config
      # Nginx configuration
      - ./conf/nginx.conf:/etc/nginx/sites-enabled/default
    ports:
      - "${WIKI_PORT}:80"
    environment:
      - WIKI_ENV=Dev
      - DB_TYPE=mysql
      - DB_SERVER=crw-local-db
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - ADMIN_USER
      - ADMIN_PASS
      - FULL_URL=http://localhost:${WIKI_PORT}
      - MEDIAWIKI_SECRET
      - WIKI_CAPTCHA_KEY
      - WIKI_CAPTCHA_SITE
      - REDIS_SERVER=crw-local-cache:6379
      - CITOID_URL=http://localhost:${CITOID_PORT}
    depends_on:
      crw-local-db:
        condition: service_started
      crw-local-cache:
        condition: service_started
  crw-local-db:
    image: mariadb:lts
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - ./data/db:/var/lib/mysql
  crw-local-cache:
    image: redis:8-bookworm
    restart: always
  crw-citoid:
    image: docker-registry.wikimedia.org/wikimedia/mediawiki-services-citoid:2025-10-28-154741-production
    ports:
      - "${CITOID_PORT}:1970"