name: CD

on:
  push:
    branches: ['main', 'release']

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Checkout the repo 
        uses: actions/checkout@v5
        with:
            submodules: recursive
        
      - name: Build container image
        run: docker build -t > ghcr.io/FULU-Foundation/crw:${GITHUB_SHA} -t ghcr.io/FULU-Foundation/crw:${GITHUB_REF_NAME} .

      - name: Log in
        run: doctl registry login --expiry-seconds 600

      - name: Push
        run: |
          docker push ghcr.io/FULU-Foundation/crw:${GITHUB_SHA}
          docker push ghcr.io/FULU-Foundation/crw:${GITHUB_REF_NAME}
